### ISSUE TITLE
Subject Registration

### ISSUE THREAD

**Issue by peseotni** [openeducat/openeducat_erp#105]
Whenever I try to approve someones subject I get the following error:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 638, in _handle_exception
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 675, in dispatch
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 331, in _call_function
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\service\model.py", line 119, in wrapper
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 324, in checked_call
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 933, in __call__
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 504, in response_wrap
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 882, in call_button
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 870, in _call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 681, in call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 672, in call_kw_multi
  File "<string>", line 2, in action_approve
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 361, in loop
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\openeducat_core\models\subject_registration.py", line 73, in action_approve
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 5195, in __getitem__
IndexError: tuple index out of range

**Comment by parthivgls** [comment]
fixed in commit 5c1eaf66f4aed8b0a8436dc1b5b9a1db7b9f02f0
