### ISSUE TITLE
Uncaught Error: QWeb2: Template 'DashboardOrgInfo' not found

### ISSUE THREAD

**Issue by SmithLin0618** [openeducat/openeducat_erp#156]
HI everyone
After I install OpenEduCat Core APP
When I want to go setting dashboard
I got this error like below：
(My odoo is ver.10.0)

--
http://35.194.157.51/web/content/251-cbe7c54/web.assets_common.js:2908
Traceback:
Error: QWeb2: Template 'DashboardOrgInfo' not found
    at Object.exception (http://35.194.157.51/web/content/251-cbe7c54/web.assets_common.js:2908:7)
    at Engine._render (http://35.194.157.51/web/content/251-cbe7c54/web.assets_common.js:2953:103)
    at Engine.render (http://35.194.157.51/web/content/251-cbe7c54/web.assets_common.js:2949:151)
    at Class.renderElement (http://35.194.157.51/web/content/251-cbe7c54/web.assets_common.js:3118:1073)
    at http://35.194.157.51/web/content/251-cbe7c54/web.assets_common.js:3118:917
    at http://35.194.157.51/web/content/251-cbe7c54/web.assets_common.js:547:681
    at fire (http://35.194.157.51/web/content/251-cbe7c54/web.assets_common.js:541:299)
    at Object.add [as done] (http://35.194.157.51/web/content/251-cbe7c54/web.assets_common.js:542:467)
    at Array.<anonymous> (http://35.194.157.51/web/content/251-cbe7c54/web.assets_common.js:547:649)
    at Function.each (http://35.194.157.51/web/content/251-cbe7c54/web.assets_common.js:370:767)

**Comment by josebarrientosq** [comment]
I got the same issue in odoo 11

**Comment by tibo-bogota** [comment]
I have exactly the same probleme. Tryed to remove and install few time and change version. The probleme still here. Odoo V10.0, Does anyone have a solution ?

**Comment by tibo-bogota** [comment]
If that can help anyone, i have found the solucion for v10. This problem come from dependency not installed. 

This should soulve the probleme:
sudo easy_install pyOpenSSL==0.13
sudo pip install pysftp

**Comment by yk134** [comment]
Hi @SmithLin0618 
We have tried with the steps that you have followed, but with our latest code, We didn't get any issue with setting -> dashboard. So can you please try with our latest code? And after that still you will get an error then please provide related screenshots and further more details.
