### ISSUE TITLE
Timetable 

### ISSUE THREAD

**Issue by HMukdadi** [openeducat/openeducat_erp#170]
when I generate timetable report I get the same error in both V10 and V11

Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_qweb\qweb.py", line 343, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_867_10350
  File "<template>", line 37, in body_call_content_10349
  File "<template>", line 38, in foreach_10348
  File "<template>", line 39, in body_call_content_10347
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\openeducat_timetable\report\timetable_report_student.py", line 87, in get_object
    timetable_obj.start_datetime).strftime(
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\openeducat_timetable\report\timetable_report_student.py", line 40, in _convert_to_local_timezone
    timezone = pytz.timezone(self._context['tz'])
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\pytz\__init__.py", line 163, in timezone
    if zone.upper() == 'UTC':
AttributeError: 'bool' object has no attribute 'upper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 1624, in report_download
    response = self.report_routes(reportname, converter='pdf', **dict(data))
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 1569, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_actions_report.py", line 628, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_actions_report.py", line 666, in render_qweb_html
    return self.render_template(self.report_name, data), 'html'
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_actions_report.py", line 470, in render_template
    return view_obj.render_template(template, values)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\app_odoo_customize\models\ir_ui_view.py", line 18, in render_template
    return super(View, self).render_template(template, values=values, engine=engine)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_ui_view.py", line 1201, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\website\models\ir_ui_view.py", line 113, in render
    return super(View, self).render(values, engine=engine)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web_editor\models\ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_ui_view.py", line 1210, in render
    return self.env[engine].render(self.id, qcontext)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_qweb\ir_qweb.py", line 57, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_qweb\qweb.py", line 272, in render
    self.compile(template, options)(self, body.append, values or {})
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_qweb\qweb.py", line 350, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.ir.ir_qweb.qweb.QWebException: 'bool' object has no attribute 'upper'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_qweb\qweb.py", line 343, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_867_10350
  File "<template>", line 37, in body_call_content_10349
  File "<template>", line 38, in foreach_10348
  File "<template>", line 39, in body_call_content_10347
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\openeducat_timetable\report\timetable_report_student.py", line 87, in get_object
    timetable_obj.start_datetime).strftime(
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\openeducat_timetable\report\timetable_report_student.py", line 40, in _convert_to_local_timezone
    timezone = pytz.timezone(self._context['tz'])
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\pytz\__init__.py", line 163, in timezone
    if zone.upper() == 'UTC':
AttributeError: 'bool' object has no attribute 'upper'

Error to render compiling AST
AttributeError: 'bool' object has no attribute 'upper'
Template: 867
Path: /templates/t/t/t/t/div/div/table[2]/tbody/tr
Node: <tr t-foreach="get_object(data)" t-as="a">
                                            <td>
                                                <span t-raw="a['name'] if  a['name']  else ''"/>
                                            </td>
                                            <td>
                                                <b>
                                                    <span t-esc="a['line'].get('0',{'subject':''})['subject']"/>
                                                </b>
                                                <br data-oe-model="ir.ui.view" data-oe-id="867" data-oe-field="arch" data-oe-xpath="/t[1]/t[1]/t[1]/t[1]/div[1]/div[1]/table[2]/tbody[1]/tr[1]/td[2]/br[1]"/>
                                                <span t-esc="a['line'].get('0',{'start_datetime':''})['start_datetime']"/>
                                            </td>
                                            <td>
                                                <b>
                                                    <span t-esc="a['line'].get('1',{'subject':''})['subject']"/>
                                                </b>
                                                <br data-oe-model="ir.ui.view" data-oe-id="867" data-oe-field="arch" data-oe-xpath="/t[1]/t[1]/t[1]/t[1]/div[1]/div[1]/table[2]/tbody[1]/tr[1]/td[3]/br[1]"/>
                                                <span t-esc="a['line'].get('1',{'start_datetime':''})['start_datetime']"/>
                                            </td>
                                            <td>
                                                <b>
                                                    <span t-esc="a['line'].get('2',{'subject':''})['subject']"/>
                                                </b>
                                                <br data-oe-model="ir.ui.view" data-oe-id="867" data-oe-field="arch" data-oe-xpath="/t[1]/t[1]/t[1]/t[1]/div[1]/div[1]/table[2]/tbody[1]/tr[1]/td[4]/br[1]"/>
                                                <span t-esc="a['line'].get('2',{'start_datetime':''})['start_datetime']"/>
                                            </td>
                                            <td>
                                                <b>
                                                    <span t-esc="a['line'].get('3',{'subject':''})['subject']"/>
                                                </b>
                                                <br data-oe-model="ir.ui.view" data-oe-id="867" data-oe-field="arch" data-oe-xpath="/t[1]/t[1]/t[1]/t[1]/div[1]/div[1]/table[2]/tbody[1]/tr[1]/td[5]/br[1]"/>
                                                <span t-esc="a['line'].get('3',{'start_datetime':''})['start_datetime']"/>
                                            </td>
                                            <td>
                                                <b>
                                                    <span t-esc="a['line'].get('4',{'subject':''})['subject']"/>
                                                </b>
                                                <br data-oe-model="ir.ui.view" data-oe-id="867" data-oe-field="arch" data-oe-xpath="/t[1]/t[1]/t[1]/t[1]/div[1]/div[1]/table[2]/tbody[1]/tr[1]/td[6]/br[1]"/>
                                                <span t-esc="a['line'].get('4',{'start_datetime':''})['start_datetime']"/>
                                            </td>
                                            <td>
                                                <b>
                                                    <span t-esc="a['line'].get('5',{'subject':''})['subject']"/>
                                                </b>
                                                <br data-oe-model="ir.ui.view" data-oe-id="867" data-oe-field="arch" data-oe-xpath="/t[1]/t[1]/t[1]/t[1]/div[1]/div[1]/table[2]/tbody[1]/tr[1]/td[7]/br[1]"/>
                                                <span t-esc="a['line'].get('5',{'start_datetime':''})['start_datetime']"/>
                                            </td>
                                            <td>
                                                <b>
                                                    <span t-esc="a['line'].get('6',{'subject':''})['subject']"/>
                                                </b>
                                                <br data-oe-model="ir.ui.view" data-oe-id="867" data-oe-field="arch" data-oe-xpath="/t[1]/t[1]/t[1]/t[1]/div[1]/div[1]/table[2]/tbody[1]/tr[1]/td[8]/br[1]"/>
                                                <span t-esc="a['line'].get('6',{'start_datetime':''})['start_datetime']"/>
                                            </td>
                                        </tr>

**Comment by dipesh-suthar-flectra** [comment]
Hello @HMukdadi 

Please check you did proper configuration of timings & also check timezone of your database. 
If still, you face the same error provide steps in details. 

Thanks

**Comment by yk134** [comment]
Hi @HMukdadi 
We have fixed this issue with PR [#166](https://github.com/openeducat/openeducat_erp/pull/166/commits/410852d90654c35c47764339b9ef40e0f0f28803)
