### ISSUE TITLE
openeducat odoo 12

### ISSUE THREAD

**Issue by peseotni** [openeducat/openeducat_erp#171]
I just installed odoo 12 fresh on my pc to test it and when I want to install openeducat I get the following error message:

`Traceback (most recent call last):
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\http.py", line 938, in __call__
    return self.method(*args, **kw)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "C:\Users\opese\Downloads\odoo-12.0\addons\web\controllers\main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "C:\Users\opese\Downloads\odoo-12.0\addons\web\controllers\main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\addons\base\models\ir_module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\addons\base\models\ir_module.py", line 442, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\addons\base\models\ir_module.py", line 535, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\modules\registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\modules\loading.py", line 426, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\modules\loading.py", line 318, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\modules\loading.py", line 224, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\modules\loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\tools\convert.py", line 792, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\tools\convert.py", line 853, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\tools\convert.py", line 745, in parse
    self.parse(rec, mode)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\tools\convert.py", line 754, in parse
    exc_info[2]
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\tools\pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\tools\convert.py", line 748, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\tools\convert.py", line 653, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\models.py", line 3795, in _load_records
    records = self.create([data['values'] for data in to_create])
  File "<decorator-gen-32>", line 2, in create
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\addons\base\models\ir_ui_view.py", line 418, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\models.py", line 3540, in create
    fields[0].determine_inverse(batch_recs)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\fields.py", line 1104, in determine_inverse
    getattr(records, self.inverse)()
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\addons\base\models\ir_ui_view.py", line 268, in _inverse_arch
    view.write(data)
  File "C:\Users\opese\Downloads\odoo-12.0\addons\website\models\ir_ui_view.py", line 70, in write
    super(View, self).write(vals)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\addons\base\models\ir_ui_view.py", line 434, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\models.py", line 3257, in write
    self._write(store_vals)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\models.py", line 3401, in _write
    self._validate_fields(vals)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\models.py", line 1100, in _validate_fields
    check(self)
  File "C:\Users\opese\Downloads\odoo-12.0\odoo\addons\base\models\ir_ui_view.py", line 353, in _check_xml
    raise ValidationError(_('Invalid view %s definition in %s') % (view.name, view.arch_fs))
odoo.tools.convert.ParseError: "Invalid view op.student.form definition in False
None" while parsing file:/c:/users/opese/downloads/odoo-12.0/addons/openeducat_core/views/student_view.xml:79, near
<record id="view_op_student_form" model="ir.ui.view">
            <field name="name">op.student.form</field>
            <field name="model">op.student</field>
            <field name="priority" eval="8"/>
            <field name="arch" type="xml">
                <form string="Student">
                    <sheet>
                        <div class="oe_title">
                            <field name="already_partner"/>
                            <label string="Already Partner"/>
                            <field name="partner_id" placeholder="Partner" options="{'no_create_edit': True}" attrs="{'required':[('already_partner','=',True)],'invisible': [('already_partner','=', False)]}"/>
                        </div>
                        <field name="image" widget="image" class="oe_left oe_avatar"/>
                        <div class="oe_title">
                            <h3>
                                <field name="title" placeholder="Title"/>
                            </h3>
                            <h1>
                                <table>
                                    <tr>
                                        <td style="padding-right:10px;">
                                            <field name="name" required="1" placeholder="First Name"/>
                                        </td>
                                        <td style="padding-right:10px;">
                                            <field name="middle_name" placeholder="Middle Name"/>
                                        </td>
                                        <td style="padding-right:10px;">
                                            <field name="last_name" placeholder="Last Name" required="1"/>
                                        </td>
                                    </tr>
                                </table>
                            </h1>
                        </div>
                        <notebook colspan="4">
                            <page name="personal_information" string="Personal Information">
                                <group col="4" colspan="4" name="personal_detail">
                                    <field name="gender" required="1"/>
                                    <field name="birth_date" required="1"/>
                                    <field name="nationality"/>
                                    <field name="visa_info"/>
                                    <field name="lang"/>
                                    <field name="blood_group"/>
                                    <field name="category_id"/>
                                    <field name="emergency_contact" context="{'show_address': 1}" options="{&quot;always_reload&quot;: True}"/>
                                    <field name="user_id" string="User" readonly="1"/>
                                    <field name="email" required="1"/>
                                </group>
                                <group string="Address Detail" name="address">
                                    <label for="type"/>
                                    <div name="div_type">
                                        <field class="oe_inline" name="type"/>
                                    </div>
                                    <label for="street" string="Address"/>
                                    <div name="div_address">
                                        <field name="street" placeholder="Street..."/>
                                        <field name="street2" placeholder="Street2"/>
                                        <div class="address_format">
                                            <field name="city" placeholder="City" style="width: 40%%"/>
                                            <field name="state_id" class="oe_no_button" placeholder="State" style="width: 37%%" options="{&quot;no_open&quot;: True}"/>
                                            <field name="zip" placeholder="ZIP" style="width: 20%%"/>
                                        </div>
                                        <field name="country_id" placeholder="Country" class="oe_no_button" options="{&quot;no_open&quot;: True}"/>
                                    </div>
                                </group>
                            </page>
                            <page name="educational" string="Educational">
                                <group col="4" colspan="4">
                                    <field name="gr_no"/>
                                </group>
                                <group>
                                    <separator string="Admission Details" colspan="4"/>
                                    <field name="course_detail_ids" nolabel="1">
                                        <tree string="Course Details">
                                            <field name="course_id"/>
                                            <field name="batch_id"/>
                                            <field name="roll_number"/>
                                            <field name="subject_ids" widget="many2many_tags"/>
                                        </tree>
                                        <form>
                                            <group cols="2" colspan="2">
                                                <field name="course_id"/>
                                                <field name="batch_id" domain="[('course_id', '=', course_id)]"/>
                                                <field name="roll_number"/>
                                            </group>
                                            <group col="4" string="Subjects">
                                                <field name="subject_ids" colspan="4" nolabel="1"/>
                                            </group>
                                        </form>
                                    </field>
                                </group>
                            </page>
                        </notebook>
                    </sheet>
                </form>
            </field>
        </record>`

Please help.

**Comment by dipesh-suthar-flectra** [comment]
Hello @peseotni 

Openeducat 12.0 version not yet released, You will be notified once it releases then you can test it with odoo 12.0. 

Thanks

**Comment by yk134** [comment]
You have to use "for" attribute in <label> tag. As it is required in odoo 12.0.
Also few more things are required like,
"alt" attribute in <img>
"name" attribute in <filter>.
