### ISSUE TITLE
Error while installing Openeducat core on V13 odoo 

### ISSUE THREAD

**Issue by mritunjaysingh34** [openeducat/openeducat_erp#395]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200215-py3.7.egg/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200215-py3.7.egg/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200215-py3.7.egg/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200215-py3.7.egg/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200215-py3.7.egg/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200215-py3.7.egg/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200215-py3.7.egg/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200215-py3.7.egg/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200215-py3.7.egg/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200215-py3.7.egg/odoo/addons/web/controllers/main.py", line 1324, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200215-py3.7.egg/odoo/addons/web/controllers/main.py", line 1312, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200215-py3.7.egg/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200215-py3.7.egg/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-58>", line 2, in button_immediate_install
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200215-py3.7.egg/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200215-py3.7.egg/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200215-py3.7.egg/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200215-py3.7.egg/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200215-py3.7.egg/odoo/modules/loading.py", line 423, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200215-py3.7.egg/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200215-py3.7.egg/odoo/modules/loading.py", line 182, in load_module_graph
    load_openerp_module(package.name)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200215-py3.7.egg/odoo/modules/module.py", line 386, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200215-py3.7.egg/odoo/addons/openeducat_core/__init__.py", line 22, in <module>
    from . import controllers
ImportError: cannot import name 'controllers' from 'odoo.addons.openeducat_core' (/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200215-py3.7.egg/odoo/addons/openeducat_core/__init__.py)

**Comment by ShakirMemon786** [comment]
@mritunjaysingh34 , I did not noticed such error at our end while installing.

**Comment by mritunjaysingh34** [comment]
I have downloaded it again and this time we are looking at Install button changed to "cancel install". 
![image](https://user-images.githubusercontent.com/60008341/78178147-d1a15780-747c-11ea-978c-d6fe31b8130a.png)

**Comment by ShakirMemon786** [comment]
@mritunjaysingh34  Go to "Apps" and click on "Apply Schedule Upgrade" to finish the installation process, all these pending modules will be installed
