### ISSUE TITLE
exception while installing OpenEducat Core

### ISSUE THREAD

**Issue by reachsukkur** [openeducat/openeducat_erp#485]
2021-03-09 04:28:10,774 15512 INFO openeducat odoo.modules.loading: loading openeducat_core/menu/openeducat_core_menu.xml 
2021-03-09 04:28:10,775 15512 ERROR openeducat odoo.tools.convert: The XML file 'c:\program files\odoo 14.0.20210307\server\odoo\addons\openeducat_core\menu\openeducat_core_menu.xml' does not fit the required schema ! 
Traceback (most recent call last):
  File "C:\Program Files\Odoo 14.0.20210307\server\odoo\tools\convert.py", line 782, in convert_xml_import
    relaxng.assert_(doc)
  File "src\lxml\etree.pyx", line 3633, in lxml.etree._Validator.assert_
AssertionError: Element odoo has extra content: data, line 3
2021-03-09 04:28:10,775 15512 WARNING openeducat odoo.tools.convert: file:/c:/program%20files/odoo%2014.0.20210307/server/odoo/addons/openeducat_core/menu/openeducat_core_menu.xml:3:0:ERROR:RELAXNGV:RELAXNG_ERR_EXTRACONTENT: Element odoo has extra content: data 
2021-03-09 04:28:10,775 15512 INFO openeducat odoo.tools.convert: Install 'jingtrang' for more precise and useful validation messages. 
2021-03-09 04:28:10,807 15512 WARNING openeducat odoo.modules.loading: Transient module states were reset 
2021-03-09 04:28:10,810 15512 ERROR openeducat odoo.modules.registry: Failed to load registry 
2021-03-09 04:28:10,810 15512 ERROR openeducat odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "C:\Program Files\Odoo 14.0.20210307\server\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "C:\Program Files\Odoo 14.0.20210307\server\odoo\http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files\Odoo 14.0.20210307\server\odoo\http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0.20210307\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0.20210307\server\odoo\http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files\Odoo 14.0.20210307\server\odoo\http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files\Odoo 14.0.20210307\server\odoo\http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files\Odoo 14.0.20210307\server\odoo\addons\web\controllers\main.py", line 1381, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\Program Files\Odoo 14.0.20210307\server\odoo\addons\web\controllers\main.py", line 1369, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files\Odoo 14.0.20210307\server\odoo\api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files\Odoo 14.0.20210307\server\odoo\api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "C:\Program Files\Odoo 14.0.20210307\server\odoo\addons\base\models\ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0.20210307\server\odoo\addons\base\models\ir_module.py", line 474, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\Program Files\Odoo 14.0.20210307\server\odoo\addons\base\models\ir_module.py", line 592, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Program Files\Odoo 14.0.20210307\server\odoo\modules\registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Program Files\Odoo 14.0.20210307\server\odoo\modules\loading.py", line 455, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Program Files\Odoo 14.0.20210307\server\odoo\modules\loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Program Files\Odoo 14.0.20210307\server\odoo\modules\loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "C:\Program Files\Odoo 14.0.20210307\server\odoo\modules\loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "C:\Program Files\Odoo 14.0.20210307\server\odoo\tools\convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "C:\Program Files\Odoo 14.0.20210307\server\odoo\tools\convert.py", line 782, in convert_xml_import
    relaxng.assert_(doc)
  File "src\lxml\etree.pyx", line 3633, in lxml.etree._Validator.assert_
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Odoo 14.0.20210307\server\odoo\http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files\Odoo 14.0.20210307\server\odoo\http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AssertionError: Element odoo has extra content: data, line 3

**Comment by parthivgls** [comment]
seems like you are trying to install the v13 app into v14.

**Comment by reachsukkur** [comment]
menuitem id="menu_openeducat_config"

this tag was the issue.
i commented "name","sequence","web_icon" then, i was able to continue the installation
