### ISSUE TITLE
'ir.actions.report.xml' object has no attribute 'generate_filename'

### ISSUE THREAD

**Issue by ssaid** [openeducat/openeducat_erp#69]
When trying to export a report (such as student->student IDCard) on front end arises this error:
`
Uncaught SyntaxError: Unexpected end of JSON input
`
And in the backend the error is:
`
AttributeError: 'ir.actions.report.xml' object has no attribute 'generate_filename'
2016-05-11 17:42:37,689 5370 ERROR jenck_demo openerp.netsvc: 'ir.actions.report.xml' object has no attribute 'generate_filename'
Traceback (most recent call last):
  File "/opt/buildout/parts/odoo/openerp/netsvc.py", line 306, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/buildout/parts/odoo/openerp/service/web_services.py", line 632, in dispatch
    res = fn(db, uid, *params)
  File "/opt/buildout/parts/odoo/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, **kw or {})
  File "/opt/buildout/parts/odoo/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, *args, **kwargs)
  File "/opt/buildout/parts/odoo/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, *args, **kw)
  File "/opt/buildout/parts/odoo/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
AttributeError: 'ir.actions.report.xml' object has no attribute 'generate_filename'`

**Comment by ssaid** [comment]
I'm developing in odoo branch 7.0
