### ISSUE TITLE
Getting error after login in odoo 16

### ISSUE THREAD

**Issue by gotorishab** [openeducat/openeducat_erp#718]
Traceback (most recent call last):
  File "/opt/odoo16/odoo16/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo16/odoo16/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo16/odoo16/odoo/http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo16/odoo16/odoo/http.py", line 1725, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo16/odoo16/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/opt/odoo16/odoo16/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo16/odoo16/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo16/odoo16/custom-addons/openeducat_erp/openeducat_core/controllers/app_main.py", line 44, in web_login
    return werkzeug.utils.redirect(redirect)
  File "/opt/odoo16/odoo16-venv/lib/python3.10/site-packages/werkzeug/utils.py", line 554, in redirect
    display_location = html.escape(location)
  File "/usr/lib/python3.10/html/__init__.py", line 19, in escape
    s = s.replace("&", "&amp;") # Must be done first!
TypeError: a bytes-like object is required, not 'str'

**Comment by Zerayacob** [comment]
I am Having the same problem too. Any leads?

**Comment by parthivgls** [comment]
use Python3.8 and not python3.10.
