### ISSUE TITLE
Unable to install web_openeducat

### ISSUE THREAD

**Issue by Starsystems-sangli** [openeducat/openeducat_erp#836]
- Odoo Server 18.0
- OpenEduCat ERP - 18.0.1.0

Below error occurring while activate

```
RPC_ERROR

Odoo Server Error

Occured on localhost:8069 on model ir.module.module and id 13 on 2024-11-15 07:26:59 GMT

Traceback (most recent call last):
  File "/home/user/projects/lms/odoo/http.py", line 1954, in _transactioning
    return service_model.retrying(func, env=self.env)
  File "/home/user/projects/lms/odoo/service/model.py", line 137, in retrying
    result = func()
  File "/home/user/projects/lms/odoo/http.py", line 1921, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/user/projects/lms/odoo/http.py", line 2168, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/user/projects/lms/odoo/addons/base/models/ir_http.py", line 329, in _dispatch
    result = endpoint(**request.params)
  File "/home/user/projects/lms/odoo/http.py", line 727, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/user/projects/lms/addons/web/controllers/dataset.py", line 40, in call_button
    action = call_kw(request.env[model], method, args, kwargs)
  File "/home/user/projects/lms/odoo/api.py", line 517, in call_kw
    result = getattr(recs, name)(*args, **kwargs)
  File "<decorator-gen-79>", line 2, in button_immediate_install
  File "/home/user/projects/lms/odoo/addons/base/models/ir_module.py", line 75, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/user/projects/lms/odoo/addons/base/models/ir_module.py", line 480, in button_immediate_install
    return self._button_immediate_function(self.env.registry[self._name].button_install)
  File "/home/user/projects/lms/odoo/addons/base/models/ir_module.py", line 604, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-13>", line 2, in new
  File "/home/user/projects/lms/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
  File "/home/user/projects/lms/odoo/modules/registry.py", line 131, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/user/projects/lms/odoo/modules/loading.py", line 479, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/home/user/projects/lms/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/user/projects/lms/odoo/modules/loading.py", line 226, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "/home/user/projects/lms/odoo/modules/loading.py", line 70, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "/home/user/projects/lms/odoo/tools/convert.py", line 608, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "/home/user/projects/lms/odoo/tools/convert.py", line 679, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/user/projects/lms/odoo/tools/convert.py", line 594, in parse
    self._tag_root(de)
  File "/home/user/projects/lms/odoo/tools/convert.py", line 548, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing None:4
Error while parsing or validating view:

Element '<xpath expr="//div[@id=&#39;snippet_structure&#39;]">' cannot be located in parent view

View error context:
{'file': '/home/user/projects/lms/lms_addons/web_openeducat/views/assets.xml',
 'line': 1,
 'name': 'snippet_id',
 'view': ir.ui.view(3012,),
 'view.model': False,
 'view.parent': ir.ui.view(1016,),
 'xmlid': 'snippet_id'}


The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPC_ERROR
        at makeErrorFromResponse (http://localhost:8069/web/assets/1/7d1b25a/web.assets_web.min.js:3091:163)
        at XMLHttpRequest.<anonymous> (http://localhost:8069/web/assets/1/7d1b25a/web.assets_web.min.js:3096:13)
```

**Comment by parthivgls** [comment]
this module will no longer going to be part of v18.
